# Generated by Django 3.0.6 on 2020-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='books',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
